[package]
name = "ppd-amd-pstate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.9.7"
zbus = "3.14.1"

[dependencies.async-std]
version = "1.12.0"
features = ["attributes"]
