// This code was autogenerated with `dbus-codegen-rust --system-bus -d net.hadess.PowerProfiles -p /net/hadess/PowerProfiles`, see https://github.com/diwic/dbus-rs
use dbus as dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;

pub trait OrgFreedesktopDBusProperties {
    fn get(&self, interface_name: &str, property_name: &str) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error>;
    fn get_all(&self, interface_name: &str) -> Result<arg::PropMap, dbus::Error>;
    fn set(&self, interface_name: &str, property_name: &str, value: arg::Variant<Box<dyn arg::RefArg>>) -> Result<(), dbus::Error>;
}

#[derive(Debug)]
pub struct OrgFreedesktopDBusPropertiesPropertiesChanged {
    pub interface_name: String,
    pub changed_properties: arg::PropMap,
    pub invalidated_properties: Vec<String>,
}

impl arg::AppendAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.interface_name, i);
        arg::RefArg::append(&self.changed_properties, i);
        arg::RefArg::append(&self.invalidated_properties, i);
    }
}

impl arg::ReadAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopDBusPropertiesPropertiesChanged {
            interface_name: i.read()?,
            changed_properties: i.read()?,
            invalidated_properties: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopDBusPropertiesPropertiesChanged {
    const NAME: &'static str = "PropertiesChanged";
    const INTERFACE: &'static str = "org.freedesktop.DBus.Properties";
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgFreedesktopDBusProperties for blocking::Proxy<'a, C> {

    fn get(&self, interface_name: &str, property_name: &str) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "Get", (interface_name, property_name, ))
            .and_then(|r: (arg::Variant<Box<dyn arg::RefArg + 'static>>, )| Ok(r.0, ))
    }

    fn get_all(&self, interface_name: &str) -> Result<arg::PropMap, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "GetAll", (interface_name, ))
            .and_then(|r: (arg::PropMap, )| Ok(r.0, ))
    }

    fn set(&self, interface_name: &str, property_name: &str, value: arg::Variant<Box<dyn arg::RefArg>>) -> Result<(), dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "Set", (interface_name, property_name, value, ))
    }
}

pub trait OrgFreedesktopDBusIntrospectable {
    fn introspect(&self) -> Result<String, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgFreedesktopDBusIntrospectable for blocking::Proxy<'a, C> {

    fn introspect(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Introspectable", "Introspect", ())
            .and_then(|r: (String, )| Ok(r.0, ))
    }
}

pub trait OrgFreedesktopDBusPeer {
    fn ping(&self) -> Result<(), dbus::Error>;
    fn get_machine_id(&self) -> Result<String, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgFreedesktopDBusPeer for blocking::Proxy<'a, C> {

    fn ping(&self) -> Result<(), dbus::Error> {
        self.method_call("org.freedesktop.DBus.Peer", "Ping", ())
    }

    fn get_machine_id(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Peer", "GetMachineId", ())
            .and_then(|r: (String, )| Ok(r.0, ))
    }
}

pub trait NetHadessPowerProfiles {
    fn hold_profile(&self, profile: &str, reason: &str, application_id: &str) -> Result<u32, dbus::Error>;
    fn release_profile(&self, cookie: u32) -> Result<(), dbus::Error>;
    fn active_profile(&self) -> Result<String, dbus::Error>;
    fn set_active_profile(&self, value: String) -> Result<(), dbus::Error>;
    fn performance_inhibited(&self) -> Result<String, dbus::Error>;
    fn performance_degraded(&self) -> Result<String, dbus::Error>;
    fn profiles(&self) -> Result<Vec<arg::PropMap>, dbus::Error>;
    fn actions(&self) -> Result<Vec<String>, dbus::Error>;
    fn active_profile_holds(&self) -> Result<Vec<arg::PropMap>, dbus::Error>;
}

#[derive(Debug)]
pub struct NetHadessPowerProfilesProfileReleased {
    pub cookie: u32,
}

impl arg::AppendAll for NetHadessPowerProfilesProfileReleased {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.cookie, i);
    }
}

impl arg::ReadAll for NetHadessPowerProfilesProfileReleased {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(NetHadessPowerProfilesProfileReleased {
            cookie: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for NetHadessPowerProfilesProfileReleased {
    const NAME: &'static str = "ProfileReleased";
    const INTERFACE: &'static str = "net.hadess.PowerProfiles";
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> NetHadessPowerProfiles for blocking::Proxy<'a, C> {

    fn hold_profile(&self, profile: &str, reason: &str, application_id: &str) -> Result<u32, dbus::Error> {
        self.method_call("net.hadess.PowerProfiles", "HoldProfile", (profile, reason, application_id, ))
            .and_then(|r: (u32, )| Ok(r.0, ))
    }

    fn release_profile(&self, cookie: u32) -> Result<(), dbus::Error> {
        self.method_call("net.hadess.PowerProfiles", "ReleaseProfile", (cookie, ))
    }

    fn active_profile(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(&self, "net.hadess.PowerProfiles", "ActiveProfile")
    }

    fn performance_inhibited(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(&self, "net.hadess.PowerProfiles", "PerformanceInhibited")
    }

    fn performance_degraded(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(&self, "net.hadess.PowerProfiles", "PerformanceDegraded")
    }

    fn profiles(&self) -> Result<Vec<arg::PropMap>, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(&self, "net.hadess.PowerProfiles", "Profiles")
    }

    fn actions(&self) -> Result<Vec<String>, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(&self, "net.hadess.PowerProfiles", "Actions")
    }

    fn active_profile_holds(&self) -> Result<Vec<arg::PropMap>, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(&self, "net.hadess.PowerProfiles", "ActiveProfileHolds")
    }

    fn set_active_profile(&self, value: String) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(&self, "net.hadess.PowerProfiles", "ActiveProfile", value)
    }
}
